Misc cleanup
fetch4/GISS-GC pull request #68
Opened 2024-12-20 17:35 UTC by jwallwork23

Follow-up from #64.

* Delete unused files that were added since E2.1.2.
* Tidy up and fix some ifdefs.

2025-02-04 18:33 UTC, jwallwork23 commented
Unfortunately the changes here don't fix the
```
 error: variable nacc_taijlh4 is already defined
```
error discussed in the meeting today.

2025-02-05 10:10 UTC, jwallwork23 commented on model/SUBDD.f
> -      call tijlh_defs(diaglists(1,k),nmax_possible,diaglens(k))
Dropping these lines fixed the issue, thanks @ltmurray!

2025-02-05 16:34 UTC, ltmurray requested changes
For the ATM_DRV changes it would be better to not delete 1019-1026, and instead remove 1036-1042. The CLOUDS2_DRV change shouldn't be necessary since we're never running with AUTOTUNE_LIGHTNING on in our applications, although the new ifdef statements appear fine.

2025-02-05 16:51 UTC, jwallwork23 commented
> For the ATM_DRV changes it would be better to not delete 1019-1026, and instead remove 1036-1042. The CLOUDS2_DRV change shouldn't be necessary since we're never running with AUTOTUNE_LIGHTNING on in our applications, although the new ifdef statements appear fine.

Thanks for reviewing this, @ltmurray. Addressed your request in 2243f11.

2025-02-11 17:12 UTC, ltmurray approved these changes

2025-02-12 09:06 UTC, merged